s390: fix implicit enum conversion
ng -Wno-unused -Wunused-value -Wunused-function -Wno-switch -Wno-char-subscripts -Wempty-body  -c -o s390-linux-tdep.o -MT s390-linux-tdep.o -MMD -MP -MF .deps/s390-linux-tdep.Tpo /home/pedro/gdb/mygit/src/gdb/s390-linux-tdep.c
/home/pedro/gdb/mygit/src/gdb/s390-linux-tdep.c: In function ‘gdbarch* s390_gdbarch_init(gdbarch_info, gdbarch_list*)’:
/home/pedro/gdb/mygit/src/gdb/s390-linux-tdep.c:3027:13: error: invalid conversion from ‘int’ to ‘s390_abi_kind’ [-fpermissive]
   tdep->abi = tdep_abi;
             ^