gdbserver/tracepoint.c: make exported IPA global int instead of enum
  src/gdb/gdbserver/tracepoint.c:4561:21: error: invalid conversion from 'int' to 'eval_result_type' [-fpermissive]